CREATE TABLE IF NOT EXISTS users(steamid TEXT PRIMARY KEY,name TEXT);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,steamid TEXT NOT NULL,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS games(
 id INTEGER PRIMARY KEY AUTOINCREMENT,steamid TEXT NOT NULL,appid INTEGER NOT NULL,name TEXT NOT NULL,
 hours REAL DEFAULT 0,genres TEXT DEFAULT '[]',ttb INTEGER,status TEXT DEFAULT 'plan',score INTEGER DEFAULT 0,
 review TEXT DEFAULT '',enriched INTEGER DEFAULT 0,platforms TEXT,UNIQUE(steamid,appid));
